### ISSUE TITLE
Custom messages

### ISSUE THREAD

**Issue by Teresa-Fernandes** [yikesinc/yikes-inc-easy-mailchimp-extender#658] opened 2017-03-07 16:38 UTC
Hi.
First of all, your plugin Easy Forms for MailChimp WordPress  is fantastic. However, I have a few questions.
Is it possible to have different custom messages for different forms? Or when i change these messages do they become available for all forms? Also, can  i use the shortcode generated on the pages on the sidebars? Thanks.
Teresa

**Comment by kpu23** [comment] 2017-03-07 16:46
Hello Teresa,

I'm glad you like the plugin! 

It is definitely possible to have different custom messages for different forms. Just head over to the form builder and click the "Custom Messages" tab. We use the same default messages for all the forms, but whenever you add a custom message it is specific to that form. 
![image](https://cloud.githubusercontent.com/assets/2415516/23667383/a966fa6a-032b-11e7-8135-a37bdcf79e01.png)


Also - you can use our shortcode in sidebars, but we also have a widget that may suit your purposes better. 

Let me know if you need anything else :-)

Cheers,
Kevin.

**Comment by Teresa-Fernandes** [comment] 2017-03-07 18:16
Thank you so much for your quick answer.

I already created two forms with different custom messages (because i am creating a bilingual website) and used them on the widgets and they worked perfectly. However, if I don't fill the required fields, the return message is displayed in only one of the languages, regardless of the page's language.

How can I make the return message appear in the correct language?

Regards

             Teresa


________________________________

**Comment by kpu23** [comment] 2017-03-07 18:20
Hi Teresa,

I'm not sure which message you're talking about, do you mean the "A required field is missing" message?

If you do mean this message, you can't customize it via the UI but we do have a filter that we can leverage to change the message. 

I can help you add a filter function to translate this message if that's what you're looking for.

Kevin.

**Comment by Teresa-Fernandes** [comment] 2017-03-07 18:36
Hi Kevin


Yes thats what i'm talking about. The message appears  in portuguese and remains the same when chose the english language. I would apreciate your help.

Regards

             Teresa


________________________________

**Comment by kpu23** [comment] 2017-03-07 18:43
Teresa,

Sorry - I'm a bit confused - I would think the message would appear in English. If it's not, then there's some language-detecting logic that's happening and I'd like to understand where that's happening before trying to add filters to change the message. Are you using some type of translation plugin? What is determining the language you're "in" (the browser)?

Let me know,
Kevin.

**Comment by Teresa-Fernandes** [comment] 2017-03-07 19:13
Kevin,


I ´m using the polylang plugin and the portuguese language is the default language.

And yes , the browser language is detected.

Do you need more information?

Let me know

 Teresa


________________________________

**Comment by kpu23** [comment] 2017-03-07 19:27
Teresa it sounds to me like the issue is actually with the polylang plugin. If it's using the browser to detect the user's language, and the message is not displaying in English, I'm not sure what there is to do about that. There is definitely an English translation for this message.

My advice is to contact the polylang folks and file a ticket with them.

I could set you up with a function that checks if the browser language is English and return the English translation, but I think the Polylang plugin would just change it back to Portuguese (we'd be stepping on each others toes and I'm not sure which translation would come through).

**Comment by Teresa-Fernandes** [comment] 2017-03-07 19:41
Kevin,

I will follow your advice.

Thank you for your attention.

Regards

            Teresa

________________________________

**Comment by kpu23** [comment] 2017-03-07 19:42
Hey Teresa,

No problem! I'm sorry I couldn't solve all the issues. I'm going to close this ticket but feel free to open a new one (or continue commenting here if it's related) if you have any more information or questions.

Hope you have a great day,
Kevin.

**Closed by kpu23** 2017-03-07 19:42 UTC

**Comment by Teresa-Fernandes** [comment] 2017-03-08 18:18
Hey Kevin,


I´m back.

Before I contacted the Polylang support team i deactivated the plugin but the problem remained. Furthermore, i tried using other forms plugins that use Mailchimp and the result is the same. With that in mind, i explored my Mailchimp settings and discovered that the default language is Portuguese. I already sent a message  to the Mailchimp support team and I am currently awaiting a response. Do you think this setting is what's causing my problem? Or could it be something else?

Regards

         Teresa





________________________________

**Comment by kpu23** [comment] 2017-03-08 18:51
Hi Teresa,

Welcome back.

I'm a bit confused. The message that I thought we were talking about before was specific to our Easy Forms plugin. Can you show me an example of the message(s) you're seeing?

Kevin.

**Comment by Teresa-Fernandes** [comment] 2017-03-08 19:10
Hi Kevin,


I send you a image that illustrate my problem.

Teresa


________________________________

**Comment by Teresa-Fernandes** [comment] 2017-03-09 15:40
Hi, Kevin


Did you understand my problem?

Regards

             Teresa

________________________________

**Comment by kpu23** [comment] 2017-03-09 17:15
Hi Teresa,

Sorry for not responding yesterday - I never received your image!

Could you please re-send it? You can either paste the image in the chatbox, or use an image hosting service and paste the URL.

Thanks,
Kevin.

**Comment by Teresa-Fernandes** [comment] 2017-03-09 21:05
Did you now, receive the image?
![screenshot](https://cloud.githubusercontent.com/assets/26255380/23770704/087399d2-050c-11e7-9e2b-795486540267.jpg)
Let me know..
 Teresa

**Comment by kpu23** [comment] 2017-03-09 21:10
Hello Teresa,

Yes - I see the image now - thank you. This message is actually coming from the browser. It is not related to (and cannot be controlled by) our MailChimp plugin, MailChimp.com, or other translation plugins.

I'm not sure why it's showing up in Portuguese for an English-language browser. If you send me a URL to your form, I can test what happens in my [English-language] browser. 

Hope that helps,
Kevin.

**Comment by Teresa-Fernandes** [comment] 2017-03-09 21:38
Hi Kevin,


You are right. I used a English  browser and the message appears in english. Did i can use a function to overcome this?

Thank you.

          Teresa


________________________________

**Comment by kpu23** [comment] 2017-03-09 21:43
Hello Teresa,

Unfortunately there's no way to change these messages. It's built-in to the browser and can't be customized.

For what it's worth, your users will probably be familiar with these messages because they will most likely have encountered it while filling out forms on other sites. Any form they fill out, on any website, will produce this message (provided they do not fill out a required field).

Kevin.

**Comment by Teresa-Fernandes** [comment] 2017-03-09 21:52
Ok Kevin.

Cheers.

                   Teresa


________________________________
