### ISSUE TITLE
Apostrophe changed to tilde

### ISSUE THREAD

**Issue by brandikelp** [yikesinc/yikes-inc-easy-mailchimp-extender#489] opened 2016-04-07 22:07 UTC
In Mailchimp, I have a Group named Mayor's Monarch Pledge.  When I am building the form, it displays correctly.  When I view the form on the website, it changes the name to Mayor~s Monarch Pledge.  I can't find anywhere to change to code to make it recognize this as a character.

**Comment by EvanHerman** [comment] 2016-04-08 00:09
Hi Brandikelp,

I setup a local test environment and was able to reproduce the issue.

We are going to take a look into the issue and see what might be going on. We'll need to patch it up to prevent the issue moving forward.

I will push this to the top of the to do list and try and make some progress on this issue tomorrow. 


Thanks,
Evan

**Comment by brandikelp** [comment] 2016-04-08 00:49
Thank you! On a side note, do you know if it is possible to make the text smaller on the widget? With the Mailchimp groups on the sign up form, it came out huge. It goes the length of the page.

Sent from my Windows Phone
________________________________

**Comment by TheTracyL** [comment] 2016-04-08 14:27
Hi there,

Do you have a link to the widget so I can take a look?

Thank you!
-Tracy

**Comment by brandikelp** [comment] 2016-04-08 20:33
I didn’t want to leave it up.  I wound up creating a new page for the form.  I put it back up temporarily and took screen shots at 100% and zoomed out so you can see how large it is.  It’s just a font sizing issue.

One other thing we noticed when we tested it is that it doesn’t recognize incorrect email addresses.  For example, I typed in my address at outlokk.com instead of outlook.com and it didn’t catch it.  Is there a setting for this?

**Comment by EvanHerman** [comment] 2016-04-08 20:36
Hi,

There is no way to validate a "valid" email address.

A "valid" email address is any combination of an @ sign, some string and a .com/.org/.net etc.

A valid email can be any domain, so `@outlokk.com` is infact a valid email address, for whoever owns the domain outlokk.com.

You can write custom validation function using JavaScript, but that's a bit outside the scope of this plugin.


Thanks,
Evan

**Comment by TheTracyL** [comment] 2016-04-08 20:36
Hello.

Can you please post links to the screen shots so I can take a look?

Thanks!
-Tracy

**Comment by brandikelp** [comment] 2016-04-08 20:42
That’s strange. I attached them to the last email, but I don’t see them.  I attached them to this one.

**Comment by TheTracyL** [comment] 2016-04-08 20:43
Hi Brandikelp,

You actually need to post them to the forums: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/489#issuecomment-207596285

Replying to notification emails doesn't go directly to us.

Thank you!
-Tracy

**Comment by brandikelp** [comment] 2016-04-11 15:33
Here are the screen captures of the widget.
![zoomed out](https://cloud.githubusercontent.com/assets/18337677/14432665/b81521fe-ffd0-11e5-8f0d-62dc61b33a95.JPG)
![capture](https://cloud.githubusercontent.com/assets/18337677/14432667/b8815464-ffd0-11e5-9586-cdf69b77f60c.JPG)

**Comment by TheTracyL** [comment] 2016-04-11 15:34
Thank you for those. It looks like the number of interest groups are causing the widget to be really long. I'm not sure how to get around that if you want to display the interest groups.

**Comment by TheTracyL** [comment] 2016-04-11 15:35
You could hide the field labels and use the placeholders instead to save some vertical space, but that will not make up for all the space used by the interest groups.

**Comment by brandikelp** [comment] 2016-04-11 15:38
I have been able to get around it with other plugins by changing the font size in the code. I just don’t have the ability to do that with this plugin. I liked the functionality of the subscribe options, but I need something that works in a sidebar.

**Comment by TheTracyL** [comment] 2016-04-11 15:52
You can totally change the font size using CSS like this:

```CSS
.widget_yikes_easy_mc_widget .yikes-easy-mc-form .yikes-easy-mc-checkbox-label {
    font-size: 10px;
}
```

You have a few options to add CSS code:

	*If you created this theme yourself, you can just add it to your style.css file
	*If you're using a theme you downloaded or bought you can make a child theme and add the code to your child theme's style.css file
	*Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.
	*You can use a plugin like <a href="https://wordpress.org/plugins/simple-custom-css/">Simple Custom CSS</a> or Jetpack and enter the code in their Custom CSS area

**Comment by brandikelp** [comment] 2016-04-11 15:54
Ok. I will give that a try.

**Comment by TheTracyL** [comment] 2016-04-11 15:54
Awesome.

**Comment by TheTracyL** [comment] 2016-04-15 20:28
This was added to the fix list, so I will close this ticket.

**Closed by TheTracyL** 2016-04-15 20:28 UTC
Labels: Bugs, High Priority
