### ISSUE TITLE
Single Optin Selected but Double Optin email being sent

### ISSUE THREAD

**Issue by lmacpherson78** [yikesinc/yikes-inc-easy-mailchimp-extender#415] opened 2015-12-12 23:47 UTC
The first form I created worked great, but the second form is sending a double optin email even though I have selected "single optin" as I did with my first form. Can you advise? Thanks.

**Comment by TheTracyL** [comment] 2015-12-15 14:06
Hi Laura.

I am going to close this ticket, because it's a duplicate of one in progress on WordPress.org

Thank you!
-Tracy

**Closed by TheTracyL** 2015-12-15 14:06 UTC
