### ISSUE TITLE
Feature Request - Allow adding classes via form customizer

### ISSUE THREAD

**Issue by chrisbloom7** [yikesinc/yikes-inc-easy-mailchimp-extender#394] opened 2015-11-02 19:51 UTC
When we were evaluating your add ons, the "Completely customize the look-and-feel of your form without needing to know any code" description for the Form Customizer stood out as being what we needed to control the look of our buttons. We're using Bootstrap as the UI framework, with a customized color scheme. We assumed that this add-on would at a minimum allow us to add some classes to the submit button, which would allow us to hook into our customized contextual button classes. After purchasing we discovered that we couldn't actually do that, and for complex buttons all we could do was to try to override Bootstrap's defaults using custom CSS, which we can do but it requires us to override quite a bit of styles to get what we want whereas it would be far easier if we could just specify some additional classes to apply to the button. Could you please add an option to the customizer to specify custom classes that would be appended to the button tag?

**Comment by TheTracyL** [comment] 2015-11-02 19:58
Hi Chris.

The button tag already has our custom classes added to it, adding more wont fix this particular issue.

The issue is, bootstrap is using a linear gradient on the `background` and our plugin adds the color code to `background-color` which will not override `background`

A fix for this, I think, would be to add both `background-color` and `background` styles to our custom stylesheet. This way we will have both all our bases covered.

I'll let Evan chime in on this issue as well.

Either way, it'll definitely be addressed in future versions.

Thank you!
-Tracy

**Comment by chrisbloom7** [comment] 2015-11-02 20:08
We appreciate the feedback you gave us for overriding the button colors via the custom CSS, and my partner was able to get that working in her tests. I now see that you are already specifying `btn-primary` on the button by default and so in that case you're correct and specifying additional contextual classes wouldn't work. Perhaps this is best accomplished via a filter in our theme. I'll take a look at that approach. Thanks.

**Comment by chrisbloom7** [comment] 2015-11-02 20:23
I'm wondering though, are you just specifying `btn btn-primary` in case end users are using Bootstrap, or do you actually require Bootstrap as a dependency? If it's more the former, maybe you could not specify those classes at all, in which case being able to specify classes on the buttons would be useful again. Those users who do use Bootstrap would just need to add the `btn btn-whatever` classes back, and those that don't use it won't notice any difference. Based on my recent theme research, not a lot of off-the-shelf themes use Bootstrap which is why we ended up rolling our own (though I admit I'm not a theme developer by trade and don't know the ecosystem intimately). Just a thought.

**Comment by TheTracyL** [comment] 2015-11-02 20:35
Your first guess is correct, we add the Bootstrap classes in case the theme uses it.

What we can do is remove those classes from the button if a user has the customizer add-on and has applied customizations to the button.

**Comment by chrisbloom7** [comment] 2015-11-02 20:42
That seems like it would be a good compromise without affecting existing functionality. Let me know if we can help test, if/when you move forward with this.

**Comment by TheTracyL** [comment] 2015-11-02 20:44
Sure thing. Thank you!

**Comment by TheTracyL** [comment] 2015-11-04 13:12
Hi Chris.

I just wanted to let you know, we added this to our to-do list for the next update to the Customizer plugin. I'm closing out this ticket, but we we have it on our list for the plugin which we keep in a private repo.

Thanks, again for your feedback!
-Tracy

**Closed by TheTracyL** 2015-11-04 13:12 UTC

**Comment by chrisbloom7** [comment] 2015-11-04 15:39
OK, thanks for the update. Looking forward to seeing it in action.
