### ISSUE TITLE
t looks like the forms table is missing. 

### ISSUE THREAD

**Issue by Dimitri18** [yikesinc/yikes-inc-easy-mailchimp-extender#512] opened 2016-06-22 14:51 UTC
t looks like the forms table is missing. Please de-activate and re-activate the plugin to attempt to create the table. If the error persists, please get in touch with the YIKES Inc. support team.

hello i checked what you already suggest by i did non fixed up, can you help me?

host siteground  - wp - baskervile 

<img width="1280" alt="schermata 2016-06-22 alle 16 50 27" src="https://cloud.githubusercontent.com/assets/20092735/16271244/7cdbe6e8-3899-11e6-89a9-a547929603af.png">

**Comment by EvanHerman** [comment] 2016-06-24 19:44
Hello,

Are you able to check the PHPMyAdmin table to see if the table exists? The table should be created when the plugin is activated. If it's not you'll hit this error. A few others have reported similar errors, but I haven't been able to get to the root of the problem.

If you'd like feel free to email us at tech@yikesinc.com

Thanks!
Evan

**Comment by EvanHerman** [comment] 2016-06-28 20:21
From some of our testing over here - it seems that the issue is the version of PHP running on the site, and the column types when the table is created.

In the next update, I am going to swap out type types of the columns so that the compatibility is a bit better across multiple versions of PHP.


Evan

**Comment by TheTracyL** [comment] 2016-07-08 00:43
I am closing this ticket, because the fix for it will be in the next update which is coming out very soon

**Closed by TheTracyL** 2016-07-08 00:43 UTC
