### ISSUE TITLE
Too many form fields show up (some multiple times)

### ISSUE THREAD

**Issue by jterschuren** [yikesinc/yikes-inc-easy-mailchimp-extender#187] opened 2015-01-14 11:23 UTC
Hi there,

I'm using your mailchimp client for wordpress for a sign up form and it's great, but I have an issue with the sign up form, as way too many fields show up (some multiple times) although in the Yikes plugin I only have these form fields: Email*, First name*, Last name*, Street, Zip / Postal Code*, City*, Country*, Language, Phone, Twitter

How can I get rid of the ones showing up additionally?

Thanks!

**Comment by EvanHerman** [comment] 2015-01-14 14:16
Hi,

Can you provide a link to your site with the form displayed?

Also, have you set up interest groups for the form? That would cause additional fields to show up on the form, in addition to the standard email , first name, last name etc.


Thanks,
Evan

**Comment by jterschuren** [comment] 2015-01-15 14:45
Hello,

here's the link: www.israelallies.eu
No interest groups set up.

**Comment by EvanHerman** [comment] 2015-01-15 14:46
Can you share what fields you have currently set up for the form? I'd like to try and reproduce the issue.

How are you displaying the form? Widget? Shortcode?

Thanks,
Evan

**Comment by jterschuren** [comment] 2015-01-15 14:50
Widget

![bildschirmfoto 2015-01-15 um 15 50 14](https://cloud.githubusercontent.com/assets/10530236/5759442/44fd443c-9cce-11e4-809b-ac2c45cdd48a.png)

**Comment by EvanHerman** [comment] 2015-01-15 14:51
k

**Comment by EvanHerman** [comment] 2015-01-15 15:07
Hi,

After setting up a form in the same way you have it setup,, and adding the widget to my sidebar I was able to display the form properly with no duplicate fields appearing, running the default TwentyTwelve theme.

This leads me to believe that it is your theme that is causing the issue. See the screenshot below.


![img](https://i.cloudup.com/Tea5BFMTbm.png)

Thanks,
Evan

**Comment by jterschuren** [comment] 2015-01-15 15:14
Hi Evan,

first of all, please send me the custom css code you're using, your fields are much nicer!
Secondly, what about this part? (This was not part of my setup): 

![bildschirmfoto 2015-01-15 um 16 12 13](https://cloud.githubusercontent.com/assets/10530236/5759925/823debdc-9cd1-11e4-9d08-35eb2dd534b4.png)

**Comment by EvanHerman** [comment] 2015-01-15 15:18
Hi,

All of the CSS is associated with the default TwentyTwelve theme. You can get all of the styles out of the style.css file. The form inherits the styles from your active theme. The way the form appears due to the styles you have declared in your active theme style.css.

The Apt/Suite City State Zip are all associated with the address field. I can see on your site that you too have the street address, apt/suite, city, state, zip fields.

This is a screenshot of your form : 
![img](https://i.cloudup.com/9l-py5L4lx.png)

**Comment by jterschuren** [comment] 2015-01-16 14:00
Yes I know the "Apt/suite, street, city, state" fields are there, but I don't have them in my setup they somehow automatically appear, without me wanting them

**Comment by EvanHerman** [comment] 2015-01-16 14:25
If the street city state is appearing, then you have set one of your fields to be an address field and not a standard text field.


Thanks,
Evan

**Comment by jterschuren** [comment] 2015-01-16 17:32
Ok, I changed that, but problem still exists!

**Comment by EvanHerman** [comment] 2015-01-16 17:33
I would try emptying your browser cache. The browser tends to cache old forms, fields and entries.


Thanks,
Evan

**Comment by jterschuren** [comment] 2015-01-16 17:34
Nope, unfortunately this isn't the reason either

**Comment by EvanHerman** [comment] 2015-01-16 17:35
Without access to your site and or your forms, this is only going to be a guessing game for me.


Thanks,
Evan

**Comment by jterschuren** [comment] 2015-01-16 17:57
I see, so which forms you need?

**Comment by EvanHerman** [comment] 2015-01-16 17:58
If you can create me a temporary login and email me at Evan@Yikesinc.com, I will login and take a look at the form. See how you are inserting it into the page, test it on a few pages, view the fields, check out the loop etc.

Thanks,
Evan

**Comment by jterschuren** [comment] 2015-01-19 12:38
How would I do that?

**Comment by EvanHerman** [comment] 2015-01-19 13:05
I'm closing this issue. If you would like continued support please email me as mentioned numerous times above. 

Thanks!
Evan

**Closed by EvanHerman** 2015-01-19 13:05 UTC

**Comment by jterschuren** [comment] 2015-01-19 13:56
Dear Evan,

I think I didn’t express myself well, my question was, how I can create a temporary account, I am quite new to Wordpress and don’t know how to do it…

Thanks!
 
Josias Terschüren

Am 19.01.2015 um 14:05 schrieb Evan Herman <notifications@github.com>:

**Comment by TheTracyL** [comment] 2015-01-19 20:40
Please email Evan directly and he can help you with that.
