### ISSUE TITLE
Subscribers keep getting 'Whoops! Something went wrong' message when signing up

### ISSUE THREAD

**Issue by madetv** [yikesinc/yikes-inc-easy-mailchimp-extender#418] opened 2015-12-29 15:03 UTC
Hi there 

We are getting the 'Whoops! Something went wrong' message when someone tries to sign up to the form from the sidebar or footer of our wordpress site: www.madetv.org please could you let me know what the trouble could be. 

Thanks!
Blaise

**Comment by EvanHerman** [comment] 2015-12-29 15:04
Hi Blaise,

I would recommend that you toggle on 'debugging' on the settings page, and trying again. That may be more telling of what the issue is.

Thanks,
Evan

**Comment by madetv** [comment] 2015-12-29 15:05
Thanks for the quick response :) Will give it a go now...

**Comment by EvanHerman** [comment] 2015-12-29 15:10
Hi Blaise,

From what I can see after you toggled on 'Debugging' - It looks like you have an 'Address' field that is required but isn't assigned to the form. You may want to uncheck 'required' to ensure it doesn't need to be filled out when filling out the form, or adding it to the form via the form builder. After one of those is completed, things should start working as expected.


Evan

**Comment by madetv** [comment] 2015-12-29 15:34
Hey Evan 

Your suggestion worked - many thanks :)

**Comment by EvanHerman** [comment] 2015-12-29 15:35
Hi Blaise,

No problem at all :)

If you're enjoying the plugin or find it at all useful we would love it if you could leave us a review in the WordPress repository:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender

I'm glad we were able to help out and get things working. Have a great rest of your day!


Evan

**Closed by EvanHerman** 2015-12-29 15:35 UTC
