### ISSUE TITLE
Issues with exporting / importing forms settings

### ISSUE THREAD

**Issue by GregorCodex** [yikesinc/yikes-inc-easy-mailchimp-extender#572] opened 2016-08-31 07:51 UTC
Hi guys, 

we have an issue with exporting/importing forms made with your plugin. Somehow, only the forms itself are being imported, but not its settings, check for example: 

http://storage8.static.itmages.com/i/16/0830/h_1472546385_9349016_dc89f478d2.png

http://storage8.static.itmages.com/i/16/0830/h_1472546316_3904170_a8875f3573.png

this settings are being skipped by importing forms. 

Would you be so kind to check, why is it happening? 

Thanx!

Regards, 

Gregor

**Comment by EvanHerman** [comment] 2016-09-13 14:59
Hi @GregorCodex,

It could be an issue with the way the data is being looped over and re-imported. We can take a look and make sure that all of the data is being transferred over properly.

We can take a look and see about getting it into the next release.

Thanks,
Evan

**Comment by GregorCodex** [comment] 2016-09-13 15:08
Hi @EvanHerman , 
thanx for getting back to me. Do you need some test environment for that or will you test it by yourself on your test install?

**Comment by EvanHerman** [comment] 2016-09-13 15:16
Hi @GregorCodex,

I can setup a test instance on my end and import/export a few times to figure out what's going on. I have a few test sites locally and live setup to test against.


Evan

**Comment by JPry** [comment] 2016-10-13 14:11
Hi @GregorCodex,

I tested the export/import process on our `staging` branch, which contains the latest updates to the plugin. I was not able to reproduce the issue you described.

Would you be wiling to test our [staging](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging) branch on your site? You can either check out the code via GitHub, or [download a zip file](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/archive/staging.zip) to test with.

**Comment by JPry** [comment] 2016-10-17 19:34
This should be resolved in the latest version 6.2.0.

**Closed** 2016-10-17 19:34 UTC
Labels: Bugs, Next Release, Suppport
