### ISSUE TITLE
Error: Warning: Invalid argument supplied for foreach() in /nas/content/staging/togwines/wp-content/plugins/yikes-inc-easy-mailchimp-extender/public/partials/shortcodes/process/process_form_submission.php on line 42

### ISSUE THREAD

**Issue by macydavid** [yikesinc/yikes-inc-easy-mailchimp-extender#411] opened 2015-12-05 00:47 UTC
Error whenever a form submits. Submission successfully goes through, however this error persists.

**Comment by EvanHerman** [comment] 2015-12-07 14:10
Hi Macydavid,

What is the exact response back? It may be due to the fact that the form has some sort of required interest group associated with it that wasn't assigned to the form.

What version of WordPress are you currently running? 


Thanks,
Evan

**Comment by kidd001** [comment] 2015-12-15 01:23
Hi There,

I'm getting the same issue, will urgently need a solution for it.

Cheers,
Kexin

**Comment by EvanHerman** [comment] 2015-12-15 01:44
Hi Kexin,

What is the issue that you are having? Have you tried switching between ajax and non-ajax? Have you confirmed that all required fields are assigned to your form?


Evan

**Comment by kidd001** [comment] 2015-12-16 21:06
Hi Evan,

I have done everything you suggested to try, but the form is still throwing the same error.

Much appreciated your help on solving this issue.

Kexin

**Comment by EvanHerman** [comment] 2015-12-16 21:16
Hi,

After some testing I have come to the conclision that NON-AJAX forms are the ones causing issues. Toggling over to an ajax form will resolve the issue. I will be closing this issue out, and will have a solution included in the next release which should be released in the next two days or so.


Evan

**Closed by EvanHerman** 2015-12-16 21:16 UTC

**Comment by kidd001** [comment] 2015-12-17 21:58
Thanks for your reply Evan,

I have tried to toggle this option but it didn't seem to be working.

![image](https://cloud.githubusercontent.com/assets/2474906/11883194/18f84420-a576-11e5-886d-bb4848e2e1be.png)

But anyway, I will be waiting for the next release and see how it goes.

Cheers

**Comment by kidd001** [comment] 2015-12-19 01:59
Hey Evan, The non-ajax form is working now!! Thank you so much for the fix! You've saved my day!

However the AJAX form is not working as it's not submitting anything into MailChimp, it's not a big deal to me, but it might be something worth for you to look into later on.
