### ISSUE TITLE
Issue with Easy Forms Plugin

### ISSUE THREAD

**Issue by Dee4DIT** [yikesinc/yikes-inc-easy-mailchimp-extender#633] opened 2017-01-24 19:01 UTC
Hello, We have appreciated your plugin, Easy Forms for MailChimp, but have had an issue since the update to the 6.3.1 version. My Google Analytics Dashboard for WP plugin stopped working, as well as some other minor issues on my WP dashboard. Today, 1/24/17, I had to rollback to version 6.2.4 in order to bring back the GA plugin to my dashboard. It seems to be working well again, as is the other minor issue. I thought there might be another updated version coming to fix these issues and that's why I've waited a week before rolling back to a previous version. Just thought you'd like to know about this issue.
Thank you for your hard work and great plugins!
Dee

**Comment by kpu23** [comment] 2017-01-25 13:44
Hi Dee4DIT,

Thanks for letting us know. Another use is having a similar problem. Currently, we're not sure what's causing it. Do you have any more information about your specific environment? What PHP version are you using? What theme?

Were you able to interact with your dashboard at all (e.g. could you open/move the widgets around) or was it completely broken?

Thanks for your patience, we're trying to resolve as soon as possible,
Kevin.

**Comment by kpu23** [comment] 2017-01-25 14:40
Hello again Dee4DIT,

I believe I've found the root cause of the error you're experiencing. It is a result of PHP version less than 5.4. I just pushed a fix to our staging branch. We're trying to release a new version today, but if you wanted to fix it quicker, you could replace your file `wp-content/plugins/yikes-inc-easy-mailchimp-extender/admin/partials/dashboard-widgets/templates/stats-list-template.php` with the file from our GitHub here: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/staging/admin/partials/dashboard-widgets/templates/stats-list-template.php.

Kevin.

**Comment by kpu23** [comment] 2017-01-25 19:16
Hello again Dee4DIT,

We just pushed an updated version (6.3.2); this should fix your problem. Please update and let us know whether it's fixed or not.

Cheers,
Kevin.

**Closed** 2017-01-25 21:19 UTC

**Comment by Dee4DIT** [comment] 2017-01-25 21:38
Hi Kevin,

I was away from my desk for a bit so didn't see your email right away. I
have updated the plugin to the new 6.3.2 version, tested a few things, and
all seems good! Thanks SO much for your very quick response and solution!
I'm impressed!! ;)

Thank you again for taking care of this issue so quickly.

Dee

**Comment by TheTracyL** [comment] 2017-01-25 21:39
Woo hoo! That's great news.

If you're enjoying the plugin and support, please consider leaving a review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make our day :-)

Thank you!
-Tracy

**Comment by Dee4DIT** [comment] 2017-01-25 22:35
Hi Tracy,
Sorry to bother you--I've been trying to leave a review but for some reason
I can't log in. It's says use the user and pw for WP.org. But that isn't
working, tho my website is open and working just fine. Am I to use the MC
login? Or the Github one? Thank you for your time.
Dee

**Comment by TheTracyL** [comment] 2017-01-25 22:39
Hi Dee,

You need to use your wordpress.org login to leave a review or use the .org forums. If you need to create an account you can do so here: https://login.wordpress.org/register/

If you have an account and lost your password, you can use this form https://login.wordpress.org/lostpassword/

Sorry for the trouble!
-Tracy
