### ISSUE TITLE
Error when user is already registered

### ISSUE THREAD

**Issue by manouallou** [yikesinc/yikes-inc-easy-mailchimp-extender#655] opened 2017-03-03 16:49 UTC
Hi and thank you for the great plugin!

I am getting an error when a user is already registered and tries to subscribe through my form.  

The message that I get is this:

> You're already subscribed. To update your profile, please **click to send yourself an update link**.

When I click the link (click to send yourself an update link) and the javascript error is this: 

`ReferenceError: update_subscriber_details_data is not defined
 /wp-content/cache/autoptimize/js/autoptimize_e648a80a8da8a278618a6aaf643203d4.js:1415`

Any ideas?

**Comment by kpu23** [comment] 2017-03-03 16:54
Hi @manouallou!

The issue is that some of the optimization that the autoptimize plugin does breaks our JavaScript files. Do you know if you're checking off the flag `Force JavaScript in <head>`? 

Here is a support ticket where I interacted with the creator of the Autoptimize plugin (super nice guy, btw), and we resolved a similar issue for another user: https://wordpress.org/support/topic/cant-create-new-forms/. If you read the discussion in that link, you can test your form without changing any settings by using the `?ao_noptimize=1` GET variable. If it works with this set, then you know you need to change some settings (and I would start first with the `Force JS in <head>` setting). 

I hope that helps - please let me know how you get along.

Cheers,
Kevin.

**Comment by manouallou** [comment] 2017-03-03 17:06
Hey, thanks for the super fast reply! Wow!

I deactivated the Autoptimize and the WP Super Cache plugins, cleared my browsers' cache but the problem persists. 

Now it just reads:

`ReferenceError: update_subscriber_details_data is not defined
 /wp-content/plugins/yikes-inc-easy-mailchimp-extender/public/js/form-submission-helpers.min.js?ver=all:1`

Any more ideas?

**Comment by kpu23** [comment] 2017-03-03 17:07
Aw, I thought this was an easy one! Drop me a link to your website and I'll poke around :-)

**Comment by manouallou** [comment] 2017-03-03 17:10
You can find the form at the bottom of this page [About](https://www.nommoswimwear.com/about/)

By the way, you outperform the Flash for sure :)

**Comment by kpu23** [comment] 2017-03-03 17:30
Hi @manouallou,

So this issue was completely my fault (apologies to Autoptimize plugin for blaming you). I just pushed an update to WordPress repo (v6.3.7) that'll fix this. 

Please comment here when you've downloaded the latest version and tested it out.

Cheers,
Kevin.

**Comment by kpu23** [comment] 2017-03-03 17:30
Also, thanks for pointing this out and being a friendly support user :-).

**Comment by manouallou** [comment] 2017-03-03 17:34
All righty then! I'll send an update when I test out the new version. For now I am just going to set the **"Update Existing Subscriber"** to **"No"**. 

I thank you (and I believe all the whole WP community) for providing such a powerful plugin and such an amazing support!

Keep up!

Regards,
Manou

**Comment by manouallou** [comment] 2017-03-03 17:40
All righty then! I'll send an update when I test out the new version. For now I am just going to set the **"Update Existing Subscriber"** to **"No"**. 

I thank you (and I believe all the whole WP community) for providing such a powerful plugin and such an amazing support!

Keep up!

Regards,
Manou

**Comment by manouallou** [comment] 2017-03-03 17:42
Yes! It works! Thank you Kevin (or should I say Flash?)

**Comment by kpu23** [comment] 2017-03-03 17:42
Worked for me (on your site)

**Comment by kpu23** [comment] 2017-03-03 17:42
You beat me to it. Guess you're the new Flash.

**Comment by kpu23** [comment] 2017-03-03 17:43
I'll close this issue :-).

Have a good weekend my friend.

**Comment by manouallou** [comment] 2017-03-03 17:43
Haha. Yeap. You can close this ticket now!

Thanks!

P.S. I am Batman by the way!

**Comment by TheTracyL** [comment] 2017-03-03 17:43
:-)

If you're enjoying the plugin and support, please consider leaving a review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make our day :-)

Thank you!
-Tracy

**Closed by kpu23** 2017-03-03 17:43 UTC
