### ISSUE TITLE
interest groups not being sent to list

### ISSUE THREAD

**Issue by garrymansfield** [yikesinc/yikes-inc-easy-mailchimp-extender#379] opened 2015-10-15 12:39 UTC
hello
I am new to easy forms and I have set up a test form on a page. I add name and email fields and these work really well into the list i have set up

However, I am interested in the forms to send specific form submissions to campaign groups as i run them. This doesnt seem to be working. I have chosen the group to select as default and also hidden the field from the form. This should do what i want which is send submissions to a group from which i can trigger and autoresponder. 

Do i need to do something different?

Regards
Garry

**Comment by EvanHerman** [comment] 2015-10-15 12:58
Hi Gary,

Welcome to the plugin! From what you describe that sounds about right. You should be able to display an interest group and set it to hidden. Each time a new subscriber signs up for the mailing list they should have the interest group assigned to their entry. 

Is the interest group not being assigned? What doesn't seem to be working as intended? Finally do you have a link to the page you are displaying the form on? That way we can take a look to see if the interest group is being applied to the form property. 


Thanks,
Evan

**Comment by garrymansfield** [comment] 2015-10-15 13:07
Hi Evan, thanks for the prompt response.

thats right it doesnt come through to mailchimp. the name email fields do
ok but not the interest group.. as per screenshot attached

http://oism.co.uk/?p=5602 is the test page i am using.

thanks Garry


Regards

*Garry Mansfield | Managing Director | Outside In Sales and Marketing Ltd *
*| oism*

*TEL *03333 444 015 | *MO *07825 815986 | *EM *garry@oism.co.uk | *WEB *
outsideinsales.marketing

**Comment by EvanHerman** [comment] 2015-10-15 13:36
Hi Gary,

It looks like the test page is password protected, or something similar. I'll do some tests on my end in the meantime.


Thanks,
Evan

**Comment by garrymansfield** [comment] 2015-10-15 13:39
doh, sorry. now fixed.

Garry

Regards

*Garry Mansfield | Managing Director | Outside In Sales and Marketing Ltd *
*| oism*

*TEL *03333 444 015 | *MO *07825 815986 | *EM *garry@oism.co.uk | *WEB *
outsideinsales.marketing

**Comment by EvanHerman** [comment] 2015-10-15 22:53
Hi Garry,

Sorry for the long delay in responses. I had a busy day fixing up some of the things in the plugin. I had a look at your issue and it was indeed a bug in the plugin.

If you update to the latest release, version 6.0.2.2, you'll find the issue has been patched up and everything should be working exactly as you had intended it to.

In your initial post here in the issue tracker, setting up a hidden interest group field will now allow you to properly assign subscribers to a given interest group depending where on the site they sign up from.

Give things a shot, and let us know how things are working with the new release.


Thanks!
Evan

**Comment by garrymansfield** [comment] 2015-10-16 07:48
works like a dream, thanks :+1:

**Closed** 2015-10-16 07:48 UTC

**Comment by EvanHerman** [comment] 2015-10-16 18:15
Awesome Garry, 

Thanks so much for keeping us updated on the issue, and I'm glad things are working smoothly and as intended. If you are enjoying the plugin, we would love it if you could leave us a nice review: https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender

Have a wonderful rest of your day and have a great weekend!
